name: Retension_Workflow_run
# troubleshoot query/list workflow action run
# curl -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/paichayon321/workflow-test/actions/runs |jq '.workflow_runs[] | .name,.id'

on:
#Set schedule
  schedule:
   # Every 5 min
    - cron: '*/5 * * * *'
   # Every day at 0:00 
   # - corn: '0 0 * * *'
#Run Manual
  workflow_dispatch:
    inputs:
      minimumRunsToKeep:
        description: 'Number of workflow runs to keep'
        required: true
        default: "10"
      workflow_name:
        description: 'Force_Workflow_name'
        required: false
        default: ""
      ManualKeep:
        description: 'Force_Keep'
        required: false
        default: "0"

jobs:
  Retension_Force_ManualFlow:
    if: ${{ github.event.inputs.workflow_name != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: paichayon321/action-delete-workflow-runs@main        
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ github.event.inputs.ManualKeep }}
          workflow_name: ${{ github.event.inputs.workflow_name }}
  
  Retension_ManualFlow_Withlist:
    if: ${{ github.event.inputs.minimumRunsToKeep != '' &&  github.event.inputs.workflow_name == '' }}
    strategy:
      matrix:
        wfname: ['Retension_Workflow_run', 'CallCustomLocal', 'CallCustomActionFlow', 'TestActionFlow' ]
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: paichayon321/action-delete-workflow-runs@main 
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ github.event.inputs.minimumRunsToKeep }}
          workflow_name: ${{ matrix.wfname }}
          
  Schedule_Retension_ManualFlow_Withlist:
    if: ${{ github.event.inputs.minimumRunsToKeep == '' }}
    strategy:
      matrix:
        wfname: ['Retension_Workflow_run', 'CallCustomLocal', 'CallCustomActionFlow', 'TestActionFlow' ]
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: paichayon321/action-delete-workflow-runs@main 
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 10
          workflow_name: ${{ matrix.wfname }}
          
#   Retension_CallCustomActionFlow:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Delete workflow runs
#         uses: mwigginsdev/delete-oldest-workflow-runs@main
#         with:
#           token: ${{ github.token }}
#           repository: ${{ github.repository }}
#           keep_minimum_runs: ${{ github.event.inputs.minimumRunsToKeep }}
#           workflow_name: "CallCustomActionFlow"

#   Retension_Retension_Workflow_run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Delete workflow runs
#         uses: mwigginsdev/delete-oldest-workflow-runs@main
#         with:
#           token: ${{ github.token }}
#           repository: ${{ github.repository }}
#           keep_minimum_runs: ${{ github.event.inputs.minimumRunsToKeep }}
#           workflow_name: "Retension_Workflow_run"
          

          
