name: Retension_Workflow_run
# troubleshoot query/list workflow action run
# curl -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/paichayon321/workflow-test/actions/runs |jq '.workflow_runs[] | .name,.id'

on:
  workflow_dispatch:
    inputs:
      minimumRunsToKeep:
        description: 'Number of workflow runs to keep'
        required: true
        default: "10"
      workflow_name:
        description: 'Workflow_name'
        required: false
        default: ""
      ManualKeep:
        description: 'ManualKeep'
        required: false
        default: "0"

jobs:
  Retension_ManualWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workflow name condition
        run: |
          if '${{ github.event.inputs.workflow_name }}' == ''; then
              # run the one command
              echo "Blank"
              wf_name=""
          else
              # run the other command
              echo "Not Blank"
              wf_name='${{ github.event.inputs.workflow_name }}'
              echo $wf_name
          fi  
          
      - name: Delete workflow runs
        uses: mwigginsdev/delete-oldest-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ github.event.inputs.ManualKeep }}
          workflow_name: ${{ wf_name }}

  Retension_CallCustomActionFlow:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: mwigginsdev/delete-oldest-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ github.event.inputs.minimumRunsToKeep }}
          workflow_name: "CallCustomActionFlow"

  Retension_Retension_Workflow_run:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: mwigginsdev/delete-oldest-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ github.event.inputs.minimumRunsToKeep }}
          workflow_name: "Retension_Workflow_run"
          
          
          
