# This is a basic workflow to help you get started with Actions

name: TestActionFlow

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  TestAction:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 0 - Checkout
        uses: actions/checkout@v2

      - name: Step 1 - Verify Checkput
        run: | 
          pwd
          ls -la
          env
        
      - name: Step 2 - Run a one-line script
        run: echo Hello, world!

      - name: Step 3 - Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  Run_Text_Banner:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 -Call Action TextBanner 
        uses: paichayon321/action-textbanner@main
        with:
          banner_text: 'Hello Toom'
 
      - name: Step 2 - Show Text Banner Result
        run: cat ./banner.txt
  Mail1:
    runs-on: ubuntu-latest
    steps:
      - name: getHostName
        run: |
          hostname
          export HOSTNAME=$(hostname)
          echo $HOSTNAME > hostname.txt
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          #body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} on host ${{ env.HOSTNAME }}
          html_body: file://hostname.txt
          to: paichayon.t@g-able.com
          from: GithubAction Notify 

